name: PyHIST
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - blas
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cycler
  - dbus
  - expat
  - ffmpeg
  - fontconfig
  - freeglut
  - freetype
  - gdk-pixbuf
  - giflib
  - glib
  - gmp
  - gnutls
  - gobject-introspection
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - icu
  - intel-openmp
  - jasper
  - jpeg
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - libedit
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libglu
  - libiconv
  - libopenblas
  - libopencv
  - libopus
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libvpx
  - libwebp
  - libxcb
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - nettle
  - numpy
  - numpy-base
  - olefile
  - openblas
  - openblas-devel
  - opencv
  - openh264
  - openjpeg
  - openslide
  - openslide-python
  - openssl
  - pandas
  - pcre
  - pillow
  - pip
  - pixman=0.36.0
  - py-opencv
  - pyparsing
  - pyqt
  - python
  - python-dateutil
  - pytz
  - qt
  - readline
  - setuptools
  - sip
  - six
  - sqlite
  - tk
  - tornado
  - wheel
  - x264
  - xz
  - zlib
  - zstd